### ISSUE TITLE
Create and use routes.dart file instead of strings.dart for routes. 

### ISSUE THREAD

**Issue by zyllus17** [TheWCKD/BlocArchitectureStartupProject#3]
As the app grows in size, the routes will also grow as well and keeping the text Strings used in the app and the routes in the same place will be anti-pattern. 
I suggest you to create a `utils` folder and under it keep the `routes.dart` file which will hold all the routes.

If you are ok with this idea, I can create a PR with the changes

**Comment by TheWCKD** [comment]
Hello, unfortunately this Repository will be deprecated soon, since I'll be switching to Very Good CLI, therefore there's no need to update it.
